/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benjamin Bardou (https://sketchfab.com/meryon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/la-renommee-louvre-museum-low-definition-556f5c7010844d8ea7b5bc16feb59d08
title: La Renommée - Louvre Museum (Low Definition)
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/assets/sculpture/scene.gltf'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 3.1]}>
        <group position={[-9.55, -3.02, -6]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            // material={materials.lambert2SG}
          >
            <meshStandardMaterial roughness={0.5} />
          </mesh>
          <mesh
            geometry={nodes.Object_4.geometry}
            // material={materials.lambert2SG}
          >
            <meshStandardMaterial roughness={0.5} />
          </mesh>
          <mesh
            geometry={nodes.Object_5.geometry}
            // material={materials.lambert2SG}
          >
            <meshStandardMaterial roughness={0.5} />
          </mesh>
          {/* <meshStandardMaterial attach="material" /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');

export default Model;
